feign:
  client:
    config:
      spacex:
        connectTimeout: 5000
        readTimeout: 5000

app:
  spacex:
    url: https://api.spacexdata.com/v3/launches
  launchLibrary:
    base: https://www.launchlibrary.net/1.4
    sub:
      mission: /mission
      launch: /launch/next/50
      missionType: /missiontype
      agency: /lsp #LSP stands for launch service provider
      agencyType: /agencytype