feign:
  client:
    config:
      spacex:
        connectTimeout: 5000
        readTimeout: 5000

app:
  spacex:
    url: https://api.spacexdata.com/v3/launches/upcoming
  launchLibrary:
    url: https://launchlibrary.net/1.4